name: Silver Spear beta 2
favicon: null
layout_spectrum: 0.10879709268920124
typography_spectrum: 0.7749812684487551
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8947732800152153
  lightness: 0.7383806006982923
  saturation: 0.10779412905685604
  rhythmicContrast: 0.6223382595926523
purpose: []
